apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
      - name: review-service
        image: gokulgkm/review-service:latest
        ports:
        - containerPort: 50053

---
apiVersion: v1
kind: Service
metadata:
  name: review-service
spec:
  type: ClusterIP
  ports:
  - port: 50053
    targetPort: 50053
  selector:
    app: review-service