apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: gokulgkm/user-service:latest
        ports:
        - containerPort: 50051
        env:
        - name: MONGO_URI
          value: "mongodb://user-mongo:27017/user_service"
        - name: JWT_SECRET
          value: "your_jwt_secret_here"

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: ClusterIP
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    app: user-service