name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies for api-gateway
      run: npm install
      working-directory: ./api-gateway

    - name: Install dependencies for frontend
      run: npm install
      working-directory: ./frontend

    - name: Install dependencies for book-service
      run: npm install
      working-directory: ./book-service

    - name: Install dependencies for review-service
      run: npm install
      working-directory: ./review-service

    - name: Install dependencies for user-service
      run: npm install
      working-directory: ./user-service

    - name: Build Docker images
      run: |
        docker build -t gokulgkm/api-gateway ./api-gateway
        docker build -t gokulgkm/frontend ./frontend
        docker build -t gokulgkm/book-service ./book-service
        docker build -t gokulgkm/review-service ./review-service
        docker build -t gokulgkm/nginx ./nginx
        docker build -t gokulgkm/user-service ./user-service

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker images
      run: |
        docker push gokulgkm/api-gateway:latest
        docker push gokulgkm/frontend:latest
        docker push gokulgkm/user-service:latest
        docker push gokulgkm/book-service:latest
        docker push gokulgkm/review-service:latest
        docker push gokulgkm/nginx:latest

    - name: Deploy to Minikube
      run: |
        minikube start --driver=docker
        kubectl apply -f k8s/